### ISSUE TITLE
Provide new SAM file 

### ISSUE THREAD

**Issue by sr320** [sr320/paper-pano-go#20]
Steven will provide new SAM file, and also add compressed version

**Comment by sr320** [comment]
A SAM file is available @

http://de.iplantcollaborative.org/dl/d/CAE61D98-6C38-4FC6-A389-F933EC647D33/bowtie.nameSorted.sam

@paolabatta  if you give me a Cyverse user name I can share directly with you there...

**Comment by paolabatta** [comment]
thank you! @sr320 my Cyverse or iPlant user names is paolabatta

**Comment by sr320** [comment]
I have also shared this whole folder with you...

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/_54__Discovery_Environment_1C8F3E99.png" alt="_54__Discovery_Environment_1C8F3E99.png"/>

might be overkill but could make it easier to run stuff in Cyverse.

**Comment by paolabatta** [comment]
Thank you that was helpful, SAM to BAm conversion is running !!

**Comment by mdelrio1** [comment]
Hi Steven
What time do you want us to meet wit you?
Please let me know
Take care
Miguel

**Comment by sr320** [comment]
How about 3pm?

**Comment by mdelrio1** [comment]
Ok,  
see you tomorrow 

Miguel

**Comment by paolabatta** [comment]
Hello @sr320 I have been trying different approaches to analyze the SAM file (you can see all the attempts I have tried in the shared analyses folder) however I have not been able to obtained a BAM file. 
I tried to installed samtools locally on my desktop but haven't been able to make it run yet. Is there a way to test that the samtools in iplant are working properly?

P.s. I might not be able to make it to the meeting since I have people at home installing a kitchen :/

**Comment by JaviRobles** [comment]
hello @sr320 my Cyverse or iPlant user names is  javirobles. Can you share the same file with me please?
