### ISSUE TITLE
How many unique contigs with annotation do we have?

### ISSUE THREAD

**Issue by sr320** [sr320/paper-pano-go#24]

**Comment by lacroix54** [comment]
Hi @sr320 
I checked over with @mdelrio1 and i was missing some data, because i thought, if we have 22974 sequences and after we obtained with the aspect P (SQL), we obtained 19483, so to prevent take duplicates, I took only the data to correspond to P (16451, but they did not have function or aspect in F or C), which correspond inside of 19483 but no correspond for all the data with the aspect P. It was my mistake.
